### PR TITLE
Added type annotations to adafruit_ahtx0.py

### PR DESCRIPTION
**Pull request by tammymakesthings**
Fixes issue #9 
- Added type annotations to `adafruit_ahtx0.py`

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
thank you @tammymakesthings  :)

**Comment by tammymakesthings** [comment]
> thank you @tammymakesthings :)

Happy to contribute - especially when in doing so I learned something valuable about a subject I thought I already understood.

**Comment by ladyada** [comment]
may we always be learning throughout our lives!

**Comment by tammymakesthings** [comment]
> may we always be learning throughout our lives!

Amen! My dad was just telling me about a guy he met recently who decided at age 70 (after a long and successful career as a doctor) to pursue his passion for physics. So he went back to college, and at age 80-something graduated with a PhD in physics.

**Pull request merged**
